### ISSUE TITLE
First contact 😃 

### ISSUE THREAD

**Issue by MatthieuHernandez** [szymonj99/szymonj99.github.io#1]
Hey Szymon, I don't know how else to contact you but I would love to help you maintain the StartingItemsGUI mod from Risk of Rain 2. Do you have some time to help with this?

**Comment by szymonj99** [comment]
👀  I'm currently busy with assignments and finishing off my course. Shoot me a discord message at `King Bugs Bunny#9671` to see what we can figure out.
